### ISSUE TITLE
clip-event reproducing

### ISSUE THREAD

**Issue by Kuangdd01** [haiyLiu/clip-event-review#1]
hello, have you finished  reproducing `clip-event` or  the first paper on `M2E2` dataset?

**Comment by haiyLiu** [comment]
@Kuangdd01 I have trained the clip-event model, but eval files of this task aren't provided. Although I don't reproduce M2E2 paper,  clip-event and M2E2 are very related.

**Comment by haiyLiu** [comment]
The dataset is so big, so I haven't upload the codes.

**Comment by Kuangdd01** [comment]
well, I tried to reproduce the `M2E2` paper but failed and it seemed that `clip-event` is also hard to replicate. I followed that paper on ACM2022 as well but the code of it seemed invalid and imperfect.

**Comment by Kuangdd01** [comment]
> 

If it is convenient for you we can exchange contact information to discuss this task? :)

**Comment by haiyLiu** [comment]
@Kuangdd01 Yes, you can add my qq number: 1454260784. Thanks.

**Comment by Kuangdd01** [comment]
> @Kuangdd01 Yes, you can add my qq number: 1454260784. Thanks.

okay
